---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.4
    env:
      TZ: "Europe/Stockholm"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "bazarr.valhalla.internal"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "bazarr.valhalla.internal"
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
    podSecurityContext:
      supplementalGroups:
      - 100
    additionalVolumeMounts:
    - name: torrents
      mountPath: "/torrents"
    - name: media
      mountPath: "/media"
    additionalVolumes:
    - name: torrents
      persistentVolumeClaim:
        claimName: nfs-torrents-pvc
    - name: media
      persistentVolumeClaim:
        claimName: nfs-media-pvc
    resources:
      requests:
        memory: 200Mi
        cpu: 150m
      limits:
        memory: 1500Mi
