---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-torrents-pv
spec:
  storageClassName: torrents
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.10
    path: /srv/nfs/torrents
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-torrents-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: torrents
  resources:
    requests:
      storage: 1Mi

