---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^([0-9]+\.[0-9]+\.[0-9]+\..*-ls.*)$'
spec:
  releaseName: qbittorrent
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts
    name: qbittorrent
    version: 6.4.0
  values:
    image:
      repository: k8sathome/qbittorrent
      tag: v4.2.5
    env:
      TZ: "America/New_York"
      PUID: 1000
      PGID: 1000
#    service:
#      additionalServices:
#      - enabled: true
#        nameSuffix: bittorrent
#        type: LoadBalancer
#        externalIPs:
#        - 10.20.50.157
#        port:
#          port: 50413
#          name: bittorrent
#          protocol: TCP
#          targetPort: 6881
#        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: torrent.valhalla.internal
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - torrent.valhalla.internal
    persistence:
      config:
        enabled: true
        existingClaim: config-torrent-pvc
    additionalVolumeMounts:
    - name: downloads
      mountPath: "/downloads"
    additionalVolumes:
    - name: downloads
      persistentVolumeClaim:
        claimName: nfs-torrents-pvc
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
