---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: "glob:3.*.*.*-ls*"
spec:
  releaseName: radarr
  # rollback:
  #   enable: true
  chart:
    repository: https://k8s-at-home.com/charts
    name: radarr
    version: 7.7.0
  values:
    image:
      repository: k8sathome/radarr
      tag: v3.0.0.4204
      # pullPolicy: Always
    env:
      TZ: "America/New_York"
      PUID: 1000
      PGID: 1000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: radarr.valhalla.internal
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - radarr.valhalla.internal
    persistence:
      config:
        enabled: true
        existingClaim: config-radarr-pvc
        size: "2Gi"
        accessMode: ReadWriteMany
    additionalVolumeMounts:
    - name: media
      mountPath: "/media"
    - name: downloads
      mountPath: "/downloads"
    additionalVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: nfs-media-pvc
    - name: downloads
      persistentVolumeClaim:
        claimName: nfs-torrents-pvc
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    podAnnotations:
      use-metadata.version-checker.io/radarr: "true"
