---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: "glob:3.*.*.*-ls*"
spec:
  releaseName: sonarr
  # rollback:
  #   enable: true
  chart:
    repository: https://k8s-at-home.com/charts
    name: sonarr
    version: 7.4.0
  values:
    image:
      repository: k8sathome/sonarr
      tag: v3.0.4.1011
      # pullPolicy: Always
    env:
      TZ: "America/New_York"
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        existingClaim: config-sonarr-pvc
        size: "2Gi"
        accessMode: ReadWriteMany
    additionalVolumeMounts:
    - name: media
      mountPath: "/media"
    - name: downloads
      mountPath: "/downloads"
    additionalVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: nfs-media-pvc
    - name: downloads
      persistentVolumeClaim:
        claimName: nfs-torrents-pvc
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    podAnnotations:
      use-metadata.version-checker.io/sonarr: "true"
