---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: "glob:3.*.*.*-ls*"
spec:
  releaseName: sonarr
  # rollback:
  #   enable: true
  chart:
    repository: https://k8s-at-home.com/charts
    name: sonarr
    version: 7.4.0
  values:
    image:
      repository: k8sathome/sonarr
      tag: v3.0.4.1011
      # pullPolicy: Always
    env:
      TZ: "America/New_York"
      PUID: 1000
      PGID: 1000
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: sonarr.holthome.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - sonarr.holthome.net
      additionalIngresses:
      - enabled: false
        nameSuffix: "api"
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: sonarr.holthome.net
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - sonarr.holthome.net
    persistence:
      config:
        enabled: true
        # storageClass: longhorn
        # size: 10Gi
        existingClaim: config-sonarr-pvc
        size: "1Gi"
        accessMode: ReadWriteMany
    additionalVolumeMounts:
    - name: downloads
      mountPath: "/media"
    additionalVolumes:
    - name: downloads
      persistentVolumeClaim:
        claimName: nfs-torrents-pvc
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    podAnnotations:
      use-metadata.version-checker.io/sonarr: "true"
