---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: "glob:3.*.*.*-ls*"
spec:
  releaseName: jackett
  # rollback:
  #   enable: true
  chart:
    repository: https://k8s-at-home.com/charts
    name: jackett
    version: 6.3.1
  values:
    image:
      repository: k8sathome/jackett
      tag: v0.17.343
      # pullPolicy: Always
    env:
      TZ: "Europe/Stockholm"
      PUID: 1000
      PGID: 1000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: jackett.valhalla.internal
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - jackett.valhalla.internal
    persistence:
      config:
        enabled: true
        existingClaim: config-jackett-pvc
        size: "2Gi"
        accessMode: ReadWriteMany
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      requests:
        memory: 200Mi
        cpu: 25m
      limits:
        memory: 500Mi
    podAnnotations:
      use-metadata.version-checker.io/jackett: "true"
