---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v3.2.2.5080
    env:
      TZ: "Europe/Stockholm"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "radarr.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "radarr.${SECRET_DOMAIN}"
      additionalIngresses:
      - enabled: true
        nameSuffix: "api"
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "radarr.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "radarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
    podSecurityContext:
      supplementalGroups:
      - 100
    additionalVolumeMounts:
    - name: torrents
      mountPath: "/torrents"
    - name: media
      mountPath: "/media"
    additionalVolumes:
    - name: torrents
      persistentVolumeClaim:
        claimName: nfs-torrents-pvc
    - name: media
      persistentVolumeClaim:
        claimName: nfs-media-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 350m
      limits:
        memory: 1500Mi
