---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:0.9.*
spec:
  releaseName: flood
  interval: 5m
  chart:
    repository: https://k8s-at-home.com/charts/
    name: flood
    version: 1.0.0
  values:
    image:
      repository: jesec/flood
      tag: 4.1.2
    env:
      FLOOD_OPTION_RUNDIR: /config
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_RTSOCKET: "/tmp/rtorrent.sock"
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: flood.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "flood.devbu.io"
    persistence:
      config:
        enabled: true
        existingClaim: config-flood-pvc
        accessMode: ReadWriteMany
        size: "1Gi"
      downloads:
        enabled: true
        existingClaim: nfs-torrents-pvc
        accessMode: ReadWriteMany
        size: "100Ti"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi

    additionalContainers:
      - name: rtorrent
        # image: billimek/alpine-rtorrent:0.9.8-1
        image: billimek/rtorrent:latest
        env:
        - name: TZ
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        ports:
        - containerPort: 49161
          name: bt
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 50Mi
        startupProbe:
          failureThreshold: 60
          periodSeconds: 10
          initialDelaySeconds: 5
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        tty: true
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /download
          name: downloads
