---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: k8sathome/qbittorrent
      tag: v4.2.5
      pullPolicy: Always
    env:
      TZ: "Europe/Stockholm"
    service:
      additionalServices:
      - enabled: false
        nameSuffix: bittorrent
        type: LoadBalancer
        externalIPs:
        - 192.168.69.130
        port:
          port: 50413
          name: bittorrent
          protocol: TCP
          targetPort: 6881
        externalTrafficPolicy: Local
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - host: qb.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "qb.devbu.io"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    additionalVolumeMounts:
    - name: downloads
      mountPath: "/downloads"
    - name: config
      mountPath: "/config"
    additionalVolumes:
    - name: downloads
      persistentVolumeClaim:
        claimName: nfs-torrents-pvc
    - name: media-serenity
      persistentVolumeClaim:
        claimName: config-flood-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi

