# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:QK0D7zKER9ltLgCf+HiU/yDrRJhB7yrR2CvSN2DT0DJc8FZEvXU9+w==,iv:dl0MWelkZBC70TKnwcVo5G5bdeAnAe92A7La9+VQpmY=,tag:MWyrYHDNL9iAxaOWC5QlWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-24T13:12:07Z"
    mac: ENC[AES256_GCM,data:zD1dxHkL3KOzMHv0tzOzsAygbi2AcZxM+2ULE3YC1jtbfET1lKp4jd1lK6ZQJW/MsGvKa7y8zL2XJCSnUlLGcWRDz35GQJmYLmBsU2kVD388OTGisi1PyVWrfSAjABxQELp5B8rVXqXdF+DYpyky67ddsIoF1VIQbtMW7s7CH4M=,iv:3tiQakuTtooAuk8JmGGiDjBvnbNcaT9grDbtfh+dkV8=,tag:Ool6L4Vs8tcSEbUxLSod2w==,type:str]
    pgp:
        - created_at: "2021-04-24T13:12:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAycSEv93WRKQAQ/7B9Guj1DsspsdBdbr6FhJTlCwC5Thz2gkXSSPJ+P7oLPr
            2NGPfc13nbgGVox7LOg3tJH8fP9sg1zI0yg7TDf3lHaqt9SmI6Qf/aqSp9wtN+X5
            RrfRhdI7yG0GlZEd2/zJqIRl6jL+c7F74TTqbyYPXg33pxo3uUZQkjWBkTImEAvz
            CJOpDcNeiCXwnPt+TdHKKGmTwsbXhA2R326nIeKgo23jJ88WSP75a7O2gUgxotct
            GD8JD6v8aN3sn0GiVHq5sv4tiw6e3ndUKnoDwXdDrMso41S+E1jUI6C8dHlQM9X+
            nUJklMji5GkXlXejdmPjhXlEDJqm4JCY23F7z++kCTWgTOzQzy1hgqyYYf6txzmY
            ko8xoG57nrus+5+uS247Efb9yk4PHpZcHSkzdeMmbK4NsPO6avux03ejFenlrYxF
            ZFdLSUBRQypFoMnpvdPMhHE61BJYB4YdzyB90/+0dB6oXaS7fVh1FEA7Lf+1Cha7
            5haOZrl5imrh5npi7nAfUTg5Lu+fwWMctp146jjBsN+CHz+H55jFp+HpAb4cmevG
            fj6SKlPZ+LIOcouHKrfKdjfqrhgzM9np7vjVRjLF1NDgElgOAB82JoZTrXf5MfVA
            tD9tXeg6DAcDw0OX96U9UHEnmiMvcItNBgFHlc9WoH0k4qUsEzyIqnmlBuHH8ifS
            XAHl9QAMcdN2SFY0iJVbCH8lRTyqc7+kQKYLCOOn5pQGcqWknsL5pHIoHdA79Wos
            U38yZCCv0+sZFafrLleZvboFZvPQ04duvFoV35tPV/Cg4EJfXqjdDmOdT0Op
            =Nrrq
            -----END PGP MESSAGE-----
          fp: 364F6CF24F8B42A60E008172BC86E8793411C046
        - created_at: "2021-04-24T13:12:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0qvTp7jL6KvAQ//dc9VmldXNPvhCZHcM/H1uRoDIvsB7GvzEhiKyBUQHrg3
            XT4QZ0ayjXnfsmMlakrm8D6pZ4r+CHmIez92dFxDDMwVCs1YpxsGUqmuQKXiGhmA
            03eO7ZXxGKOPIgWyp0YmiGWMzmrQzhSCb0m+/UKMn/0xydBFe5KzX932+aqD/elr
            W+GDHBxMTf4J+/e9rCqwsa81WZYBSWEMVTAv2gqvJs0L+FmF8GGwdxVaI498NEZD
            ONmbDxFiHhSDsvaWb/y+NNnyw6aJV86924foPTUS4ATik8Rf9V3OlWEbpBmPAu6q
            UpmChTi0vBiJLePK7E9UCAFCLt3yz2BIQ7S/KC1jvhS3pW2ftK3j1839k7pNd4X9
            wH9PurQMvu4ZPyBp+6rpNMXwTojYyFvffHbXHUHBiHwRrQW4OOnshL5FCUSrVHNS
            qD1LWaoVvaqg6orRlmsqnTwxE+pnY5y9pkdqWLlUhe2NEMZI7aXQ+3wAJUXKVKS4
            RyH/eBp7D8GUtVjEUoWEihvJGsAL7DR8hK8yT0IibQaBxcoyJEjvCieWoG8MsQC0
            V7KFQAiRRgMsB/L0htGoSbAzAlp7wojHmBuwNDzZbyEQ7ZlC47/5ZZ4oJt5HH0Jy
            2QNjco4zlV0va1sYcVdo8+KDQCOwUC4qgY1yJwFfGDJanc1iR4lo7oXQJDEzOrDS
            XAET22aunimdjKTqYKtwcAAEH/5IxRQkeLYma1x+mfQJmgTNBFp7wqYPmshCnBaY
            mZJQeRh5V+YhekPlKomqcMseBcMwy1LL7TBP6HJBqPd407t1cW7aJ1rY/Xvq
            =P5gV
            -----END PGP MESSAGE-----
          fp: 726584468150B8F4F60DCE4E5C36B91C94A80A1C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
