name: CI

on: [push, pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm v3 in root dir
        uses: stefanprodan/hrval-action@v2.9.0
        with:
          helmRelease: ./
          helmVersion: v3
          kubernetesVersion: 1.17.0
          ignoreValues: true

