name: CI

on: [push, pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Helm v3 in root dir
        uses: stefanprodan/hrval-action@master
        with:
          helmRelease: ./
          helmVersion: v3
          kubernetesVersion: 1.17.0
          ignoreValues: true

